config/routes.rb
Ooshkaboosh::Application.routes.draw do
  resources :ooshes

end

app/models/oosh.rb
class Oosh < ActiveRecord::Base
  attr_accessible :extra_text, :full_text, :keyword, :stamp
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ooshes_controller.rb
class OoshesController < ApplicationController
  # GET /ooshes
  # GET /ooshes.json
  def index
    @ooshes = Oosh.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ooshes }
    end
  end

  # GET /ooshes/1
  # GET /ooshes/1.json
  def show
    @oosh = Oosh.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @oosh }
    end
  end

  # GET /ooshes/new
  # GET /ooshes/new.json
  def new
    @oosh = Oosh.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @oosh }
    end
  end

  # GET /ooshes/1/edit
  def edit
    @oosh = Oosh.find(params[:id])
  end

  # POST /ooshes
  # POST /ooshes.json
  def create
    @oosh = Oosh.new(params[:oosh])

    respond_to do |format|
      if @oosh.save
        format.html { redirect_to @oosh, notice: 'Oosh was successfully created.' }
        format.json { render json: @oosh, status: :created, location: @oosh }
      else
        format.html { render action: "new" }
        format.json { render json: @oosh.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ooshes/1
  # PUT /ooshes/1.json
  def update
    @oosh = Oosh.find(params[:id])

    respond_to do |format|
      if @oosh.update_attributes(params[:oosh])
        format.html { redirect_to @oosh, notice: 'Oosh was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @oosh.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ooshes/1
  # DELETE /ooshes/1.json
  def destroy
    @oosh = Oosh.find(params[:id])
    @oosh.destroy

    respond_to do |format|
      format.html { redirect_to ooshes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ooshes_helper.rb
module OoshesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ooshkaboosh</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ooshes/_form.html.erb
<%= form_for(@oosh) do |f| %>
  <% if @oosh.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oosh.errors.count, "error") %> prohibited this oosh from being saved:</h2>

      <ul>
      <% @oosh.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_text %><br />
    <%= f.text_field :full_text %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :extra_text %><br />
    <%= f.text_field :extra_text %>
  </div>
  <div class="field">
    <%= f.label :stamp %><br />
    <%= f.datetime_select :stamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ooshes/edit.html.erb
<h1>Editing oosh</h1>

<%= render 'form' %>

<%= link_to 'Show', @oosh %> |
<%= link_to 'Back', ooshes_path %>

app/views/ooshes/index.html.erb
<h1>Listing ooshes</h1>

<table>
  <tr>
    <th>Full text</th>
    <th>Keyword</th>
    <th>Extra text</th>
    <th>Stamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ooshes.each do |oosh| %>
  <tr>
    <td><%= oosh.full_text %></td>
    <td><%= oosh.keyword %></td>
    <td><%= oosh.extra_text %></td>
    <td><%= oosh.stamp %></td>
    <td><%= link_to 'Show', oosh %></td>
    <td><%= link_to 'Edit', edit_oosh_path(oosh) %></td>
    <td><%= link_to 'Destroy', oosh, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Oosh', new_oosh_path %>

app/views/ooshes/new.html.erb
<h1>New oosh</h1>

<%= render 'form' %>

<%= link_to 'Back', ooshes_path %>

app/views/ooshes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Full text:</b>
  <%= @oosh.full_text %>
</p>

<p>
  <b>Keyword:</b>
  <%= @oosh.keyword %>
</p>

<p>
  <b>Extra text:</b>
  <%= @oosh.extra_text %>
</p>

<p>
  <b>Stamp:</b>
  <%= @oosh.stamp %>
</p>


<%= link_to 'Edit', edit_oosh_path(@oosh) %> |
<%= link_to 'Back', ooshes_path %>